---
- name: Converge ansible
  hosts: all
  become: true

  roles:
    - role: serpro69.workstation.ansible
      vars:
        ansible_packages:
          - yamllint # skip ansible-lint due to it's dependencies making idempotency play fail
