---
# optional path to an existing virtual environment to install ansible to
# setting this variable does NOT install virtual environment itself if it doesn't exist
ansible_virtualenv:

# additional packages for ansible
ansible_packages:
  - ansible-lint
  - yamllint

# additional dependencies that are required by some ansible modules
ansible_dependencies:
  - jmespath # community.general.json_query
  - dnspython # community.general.nsupdate
  - lxml # community.general.xml

ansible_install_molecule: true
ansible_molecule_plugins:
  - docker
