---
dependency:
  name: shell
  command: ansible-galaxy collection install --force .
  env:
    ANSIBLE_ROLES_PATH: molecule/galaxy/roles
    ANSIBLE_COLLECTIONS_PATH: molecule/galaxy
driver:
  name: docker
platforms:
  - name: ubuntu2004
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    privileged: true
    pre_build_image: true
  - name: ubuntu2204
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    privileged: true
    pre_build_image: true
lint: |
  set -e
  ansible-lint
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: molecule/galaxy/roles
    ANSIBLE_COLLECTIONS_PATH: molecule/galaxy
verifier:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: molecule/galaxy/roles
    ANSIBLE_COLLECTIONS_PATH: molecule/galaxy
