---
- name: Install for --user
  when: not ansible_virtualenv
  block:
    - name: Ensure ansible for user # noqa package-latest
      ansible.builtin.pip:
        name: ansible
        extra_args: --user
        state: latest

    - name: Ensure ansible dependencies for user # noqa package-latest
      ansible.builtin.pip:
        name: "{{ ansible_packages | default([]) | union(ansible_dependencies | default([])) | list | unique }}"
        extra_args: --user
        state: latest

    - name: Ensure molecule user # noqa package-latest
      ansible.builtin.pip:
        name: "{{ ['molecule'] | union(ansible_molecule_plugins | default([])) | list | unique }}"
        extra_args: --user
        state: latest
      when: ansible_install_molecule | bool


- name: Check virtualenv exists
  ansible.builtin.stat:
    path: "{{ ansible_virtualenv }}"
  register: _stat_ansible_virtualenv
  when:
    - ansible_virtualenv is string
    - ansible_virtualenv | length > 0

- name: Install in virtualenv
  when:
    - _stat_ansible_virtualenv.stat is defined
    - _stat_ansible_virtualenv.stat.exists
    - _stat_ansible_virtualenv.stat.isdir
  block:
    - name: Ensure ansible in virtualenv # noqa package-latest
      ansible.builtin.pip:
        name: ansible
        state: latest
        virtualenv: "{{ ansible_virtualenv }}"

    - name: Ensure ansible dependencies in virtualenv # noqa package-latest
      ansible.builtin.pip:
        name: "{{ ansible_packages | default([]) | union(ansible_dependencies | default([])) | list | unique }}"
        state: latest
        virtualenv: "{{ ansible_virtualenv }}"

    - name: Ensure molecule in virtualenv # noqa package-latest
      ansible.builtin.pip:
        name: "{{ ['molecule'] | union(ansible_molecule_plugins | default([])) | list | unique }}"
        state: latest
        virtualenv: "{{ ansible_virtualenv }}"
      when: ansible_install_molecule | bool
