---
# https://github.com/junegunn/vim-plug#neovim
- name: Install vim-plug
  ansible.builtin.command:
    cmd: >-
      curl -fLo {{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim
      --create-dirs
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  creates: "{{ ansible_env.HOME}}/.local/share/nvim/site/autoload/plug.vim"
  when: not (nvim_use_flatpak | bool)
  become: false

- name: Install vim-plug for flatpak
  ansible.builtin.command:
    cmd: >-
      curl -fLo {{ ansible_env.HOME}}/.var/app/io.neovim.nvim/data/nvim/site/autoload/plug.vim
      --create-dirs
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  creates: "{{ ansible_env.HOME}}/.var/app/io.neovim.nvim/data/nvim/site/autoload/plug.vim"
  when: nvim_use_flatpak | bool
  become: false
